#Author: vkotteda
#maintainer <kvmkrao@gmail.com>

FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
      && apt-get install -y \
      git-core build-essential cmake libfl-dev bison zlib1g-dev qttools5-dev qtbase5-dev libqt5x11extras5-dev gnuplot \
			libreadline-dev libncurses-dev libxt-dev libopenmpi-dev openmpi-bin libboost-system-dev libboost-thread-dev libgmp-dev \
			libmpfr-dev python python-dev libcgal-dev curl \
			gcc g++ \
			cmake \
      git \
      wget \
      vim       \
      software-properties-common ;\
      rm -rf /var/lib/apt/lists/*

RUN useradd --user-group --create-home --shell /bin/bash foam ;\
        echo "foam ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers


USER foam 
RUN mkdir $HOME/foam/
ARG WORKDIR=$HOME/foam/OpenFOAM-9

SHELL ["/bin/bash", "-c"]

RUN git clone https://github.com/OpenFOAM/OpenFOAM-9.git $HOME/foam/OpenFOAM-9 
RUN git clone https://github.com/OpenFOAM/ThirdParty-9.git $HOME/foam/ThirdParty-9

RUN source $HOME/foam/OpenFOAM-9/etc/bashrc
RUN echo "alias of9='source /home/foam/foam/OpenFOAM-9/etc/bashrc'" >> $HOME/.bashrc

WORKDIR $HOME/foam/OpenFOAM-9
RUN export QT_SELECT=qt5
RUN export QT_BIN_DIR=/usr/bin/
RUN source /home/foam/foam/OpenFOAM-9/etc/bashrc

WORKDIR /home/foam//foam/OpenFOAM-9
CMD ["/bin/bash", "-c"] 
RUN export WM_PROJECT_DIR=/home/foam/foam/OpenFOAM-9
RUN source etc/bashrc && ./Allwmake

USER foam 
